version: '2'
services:
  SMTP_Server:
    image: 'm96dg/pw_smtp_postfix:latest'
    stdin_open: true
    tty: true
    networks:
      network_0: {}
networks:
  network_0:
    ipam:
      config:
        - subnet: 193.20.1.1/24
